set(_AMENT_PACKAGE_NAME "mid70pp")
set(mid70pp_VERSION "0.0.0")
set(mid70pp_MAINTAINER "rm_lidar <rm_lidar@todo.todo>")
set(mid70pp_BUILD_DEPENDS "rclcpp" "std_msgs" "sensor_msgs")
set(mid70pp_BUILDTOOL_DEPENDS "ament_cmake")
set(mid70pp_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "sensor_msgs")
set(mid70pp_BUILDTOOL_EXPORT_DEPENDS )
set(mid70pp_EXEC_DEPENDS "rclcpp" "std_msgs" "sensor_msgs")
set(mid70pp_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(mid70pp_GROUP_DEPENDS )
set(mid70pp_MEMBER_OF_GROUPS )
set(mid70pp_DEPRECATED "")
set(mid70pp_EXPORT_TAGS)
list(APPEND mid70pp_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
